version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: kenangan
      DB_PASSWORD: kenangan
      DB_NAME: kenangan_commerce
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev

volumes:
  db_data:
    driver: local
